import { execFileSync } from "child_process";
import {
  ImpactAnalyzer,
  VerifyEngine,
  StructuralMetrics,
  redactReport,
} from "ariadne-core";
import { getContext } from "../lib/context";
import { output, outputError } from "../lib/output";

function extractFlag(args: string[], flag: string): string | undefined {
  const idx = args.indexOf(flag);
  if (idx !== -1 && idx + 1 < args.length) {
    return args[idx + 1];
  }
  return undefined;
}

/**
 * Get changed files by diffing against a base branch.
 * Falls back to listing all tracked files if diff fails (e.g. shallow clone).
 */
function getChangedFiles(repoRoot: string, baseBranch: string): string[] {
  try {
    // Ensure we have the base branch ref (CI may be a shallow clone)
    try {
      execFileSync("git", ["fetch", "origin", baseBranch, "--depth=1"], {
        cwd: repoRoot,
        stdio: ["pipe", "pipe", "pipe"],
        timeout: 30_000,
      });
    } catch {
      // May already have the ref — continue
    }

    const raw = execFileSync(
      "git",
      ["diff", "--name-only", `origin/${baseBranch}...HEAD`],
      {
        cwd: repoRoot,
        encoding: "utf-8",
        timeout: 10_000,
      },
    );
    return raw
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean);
  } catch {
    // Fallback: diff against HEAD~1
    try {
      const raw = execFileSync("git", ["diff", "--name-only", "HEAD~1"], {
        cwd: repoRoot,
        encoding: "utf-8",
        timeout: 10_000,
      });
      return raw
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean);
    } catch {
      return [];
    }
  }
}

/**
 * Generate a markdown PR comment from the CI report data.
 */
function generateMarkdown(report: CiReport): string {
  const { summary, impact, verify } = report;

  const riskIcon =
    summary.riskCategory === "critical"
      ? "🔴"
      : summary.riskCategory === "high"
        ? "🟠"
        : summary.riskCategory === "medium"
          ? "🟡"
          : "🟢";

  const policyIcon = summary.policyPassed ? "✅" : "❌";
  const policyText = summary.policyPassed ? "PASSED" : "FAILED";

  let md = `## 🔍 Ariadne Structural Report\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Impact Radius | ${summary.impactRadius} files |\n`;
  md += `| Risk Score | ${summary.riskScore.toFixed(2)} ${riskIcon} ${summary.riskCategory} |\n`;
  md += `| Public API Breaks | ${summary.publicApiBreaks} |\n`;
  md += `| New Cycles | ${summary.newCycles} |\n`;
  md += `| Tests Found | ${summary.testCount} |\n`;
  md += `| Policy | ${policyIcon} ${policyText} |\n`;

  // Verification issues
  if (verify.failedChecks.length > 0) {
    md += `\n### Verification Issues\n\n`;
    for (const check of verify.failedChecks) {
      md += `- ❌ **${check.name}**: ${check.summary}\n`;
    }
  }

  // Top affected files (limit to 10)
  if (impact.topAffectedFiles.length > 0) {
    md += `\n### Impact Details\n\n`;
    md += `<details><summary>${impact.topAffectedFiles.length} affected files</summary>\n\n`;
    for (const f of impact.topAffectedFiles) {
      md += `- \`${f.path}\` (depth ${f.depth}) — ${f.reason}\n`;
    }
    md += `\n</details>\n`;
  }

  md += `\n---\n<sub>Generated by <a href="https://github.com/simonrueba/ariadne">Ariadne</a> — structural intelligence for AI coding agents</sub>\n`;

  return md;
}

interface CiReport {
  changedFiles: string[];
  impact: {
    riskScore: number;
    riskCategory: string;
    affectedFileCount: number;
    publicApiBreaks: number;
    testCount: number;
    topAffectedFiles: { path: string; depth: number; reason: string }[];
  };
  verify: {
    status: string;
    passed: boolean;
    failedChecks: { name: string; summary: string }[];
  };
  metrics: {
    newCycles: number;
    couplingChanges: number;
  };
  summary: {
    riskScore: number;
    riskCategory: string;
    policyPassed: boolean;
    impactRadius: number;
    publicApiBreaks: number;
    newCycles: number;
    testCount: number;
  };
  markdown: string;
}

/**
 * CI command — single command for GitHub Actions / CI pipelines.
 *
 * Usage:
 *   ariadne ci [--base main] [--markdown] [--root <path>]
 *
 * Runs impact analysis on changed files, verification, and metrics.
 * Outputs structured JSON (default) or markdown PR comment.
 */
export async function runCi(args: string[]): Promise<void> {
  const baseBranch = extractFlag(args, "--base") ?? "main";
  const formatMarkdown = args.includes("--markdown");
  const rootArg = extractFlag(args, "--root");
  const repoRoot = rootArg || process.cwd();

  // 1. Get changed files
  const changedFiles = getChangedFiles(repoRoot, baseBranch);

  if (changedFiles.length === 0) {
    const emptyReport: CiReport = {
      changedFiles: [],
      impact: {
        riskScore: 0,
        riskCategory: "low",
        affectedFileCount: 0,
        publicApiBreaks: 0,
        testCount: 0,
        topAffectedFiles: [],
      },
      verify: { status: "OK", passed: true, failedChecks: [] },
      metrics: { newCycles: 0, couplingChanges: 0 },
      summary: {
        riskScore: 0,
        riskCategory: "low",
        policyPassed: true,
        impactRadius: 0,
        publicApiBreaks: 0,
        newCycles: 0,
        testCount: 0,
      },
      markdown: "## 🔍 Ariadne Structural Report\n\nNo changed files detected.\n",
    };
    if (formatMarkdown) {
      console.log(emptyReport.markdown);
    } else {
      output("ci_report", emptyReport);
    }
    return;
  }

  // 2. Get context (index must exist — setup should run before ci)
  let ctx;
  try {
    ctx = getContext(rootArg);
  } catch {
    outputError(
      "NOT_INITIALIZED",
      "Ariadne index not found. Run 'ariadne setup' first.",
    );
  }

  try {
    // 3. Impact analysis on changed files
    const analyzer = new ImpactAnalyzer(ctx.store, ctx.repoRoot);
    const impactResult = analyzer.computeTransitiveImpact(changedFiles);

    // 4. Verification
    const engine = new VerifyEngine(ctx.store, ctx.ledger, ctx.repoRoot);
    const verifyResult = await engine.verify();
    const redacted = redactReport(verifyResult);

    // 5. Metrics diff (if baseline exists)
    const metricsEngine = new StructuralMetrics(ctx.store, ctx.repoRoot);
    const baseline = metricsEngine.loadSnapshot();
    let newCycles = 0;
    let couplingChanges = 0;
    if (baseline) {
      const current = metricsEngine.computeMetrics();
      const diff = metricsEngine.diff(current, baseline);
      newCycles = diff.newCycles.length;
      couplingChanges = diff.couplingIncreases.length;
    }

    // 6. Build failed checks summary
    const failedChecks: { name: string; summary: string }[] = [];
    const checks = redacted.checks as Record<string, any>;
    for (const [name, check] of Object.entries(checks)) {
      if (check && !check.passed) {
        const issues = check.issues ?? check.errors ?? [];
        const count = Array.isArray(issues) ? issues.length : 0;
        const firstMsg =
          count > 0 && issues[0]?.message
            ? issues[0].message
            : `${count} issue(s)`;
        failedChecks.push({ name, summary: firstMsg });
      }
    }

    // 7. Build report
    const report: CiReport = {
      changedFiles,
      impact: {
        riskScore: impactResult.riskScore,
        riskCategory: impactResult.riskCategory,
        affectedFileCount: impactResult.affectedFiles.length,
        publicApiBreaks: impactResult.publicApiBreaks.length,
        testCount: impactResult.testCount,
        topAffectedFiles: impactResult.affectedFiles.slice(0, 10),
      },
      verify: {
        status: verifyResult.status,
        passed: verifyResult.status === "OK",
        failedChecks,
      },
      metrics: { newCycles, couplingChanges },
      summary: {
        riskScore: impactResult.riskScore,
        riskCategory: impactResult.riskCategory,
        policyPassed: verifyResult.status === "OK",
        impactRadius: impactResult.affectedFiles.length,
        publicApiBreaks: impactResult.publicApiBreaks.length,
        newCycles,
        testCount: impactResult.testCount,
      },
      markdown: "",
    };

    report.markdown = generateMarkdown(report);

    if (formatMarkdown) {
      console.log(report.markdown);
    } else {
      output("ci_report", report);
    }

    // Exit non-zero if verification failed
    if (verifyResult.status !== "OK") {
      process.exit(1);
    }
  } finally {
    ctx.db.close();
  }
}
