import { existsSync, mkdirSync, writeFileSync, readFileSync, appendFileSync, copyFileSync, chmodSync, readdirSync, statSync } from "fs";
import { join, resolve } from "path";
import { createDatabase } from "ariadne-core";
import { output } from "../lib/output";
import { runIndex } from "./index-cmd";

/**
 * One-command setup for any project: init + index + generate configs.
 *
 * Usage:
 *   ariadne setup [path]           # init + structural + SCIP index
 *   ariadne setup [path] --quick   # init + structural imports only (skip SCIP)
 */
export async function runSetup(args: string[]): Promise<void> {
  const quick = args.includes("--quick");
  const rootArg = args.find((a) => !a.startsWith("--"));
  const repoRoot = resolve(rootArg || process.cwd());
  const ariadneDir = join(repoRoot, ".ariadne");

  const steps: { step: string; status: string }[] = [];

  // Step 1: Init (idempotent — safe to re-run)
  mkdirSync(ariadneDir, { recursive: true });
  mkdirSync(join(ariadneDir, "cache", "scip"), { recursive: true });

  const dbPath = join(ariadneDir, "index.db");
  const db = createDatabase(dbPath);
  db.close();

  if (!existsSync(join(ariadneDir, "state.json"))) {
    writeFileSync(
      join(ariadneDir, "state.json"),
      JSON.stringify({ version: 1, createdAt: new Date().toISOString(), repoRoot }, null, 2),
    );
  }
  steps.push({ step: "init", status: "ok" });

  // Step 2: Add .ariadne/ to .gitignore
  const gitignorePath = join(repoRoot, ".gitignore");
  const gitignoreEntry = ".ariadne/";
  if (existsSync(gitignorePath)) {
    const content = readFileSync(gitignorePath, "utf-8");
    if (!content.includes(gitignoreEntry)) {
      appendFileSync(gitignorePath, `\n${gitignoreEntry}\n`);
    }
  } else {
    writeFileSync(gitignorePath, `${gitignoreEntry}\n`);
  }
  steps.push({ step: "gitignore", status: "ok" });

  // Step 2b: Auto-generate ariadne.boundaries.json for monorepos
  const boundariesPath = join(repoRoot, "ariadne.boundaries.json");
  if (!existsSync(boundariesPath)) {
    const packagesDir = join(repoRoot, "packages");
    if (existsSync(packagesDir)) {
      try {
        const pkgs = readdirSync(packagesDir).filter((name) => {
          try {
            return statSync(join(packagesDir, name)).isDirectory();
          } catch {
            return false;
          }
        });
        if (pkgs.length > 0) {
          // Generate restrictive defaults: leaf packages can import "core" (if it exists),
          // but not each other. This is a meaningful starting point — edit to match your
          // actual architecture.
          const hasCore = pkgs.includes("core");
          const layers: Record<string, { path: string; canImport: string[]; _comment?: string }> = {};
          for (const pkg of pkgs) {
            const canImport: string[] = [];
            if (pkg !== "core" && hasCore) {
              canImport.push("core");
            }
            layers[pkg] = {
              path: `packages/${pkg}/`,
              canImport,
            };
          }
          layers._comment = {
            path: "",
            canImport: [],
            _comment: "Auto-generated placeholder. Edit canImport arrays to match your architecture.",
          } as any;
          // Remove the _comment hack and use a top-level note instead
          delete layers._comment;
          const config = {
            _comment: "Auto-generated by ariadne setup. Edit canImport arrays to match your architecture.",
            layers,
          };
          writeFileSync(
            boundariesPath,
            JSON.stringify(config, null, 2) + "\n",
          );
          steps.push({ step: "boundaries_config", status: "created" });
        }
      } catch {
        // Ignore errors during boundary config generation
      }
    }
  }

  // Step 3: Copy portable hook scripts into .ariadne/hooks/
  const hooksDir = join(ariadneDir, "hooks");
  mkdirSync(hooksDir, { recursive: true });
  const srcHooksDir = join(import.meta.dir, "..", "hooks");
  for (const hookFile of ["post-edit.sh", "post-test.sh", "stop-verify.sh", "pre-edit-impact.sh"]) {
    const src = join(srcHooksDir, hookFile);
    const dest = join(hooksDir, hookFile);
    if (existsSync(src)) {
      copyFileSync(src, dest);
      chmodSync(dest, 0o755);
    }
  }
  steps.push({ step: "hooks_copied", status: "ok" });

  // Step 4: Generate .claude/settings.json for hooks (if not present)
  const claudeDir = join(repoRoot, ".claude");
  const settingsPath = join(claudeDir, "settings.json");
  if (!existsSync(settingsPath)) {
    mkdirSync(claudeDir, { recursive: true });
    const hooksConfig = generateHooksConfig();
    writeFileSync(settingsPath, JSON.stringify(hooksConfig, null, 2) + "\n");
    steps.push({ step: "hooks_config", status: "created" });
  } else {
    steps.push({ step: "hooks_config", status: "exists" });
  }

  // Step 5: Generate .mcp.json for MCP server (if not present)
  const mcpPath = join(repoRoot, ".mcp.json");
  if (!existsSync(mcpPath)) {
    const mcpConfig = generateMcpConfig();
    writeFileSync(mcpPath, JSON.stringify(mcpConfig, null, 2) + "\n");
    steps.push({ step: "mcp_config", status: "created" });
  } else {
    steps.push({ step: "mcp_config", status: "exists" });
  }

  // Step 6: Run index
  if (quick) {
    // Quick mode: structural imports only, skip SCIP indexers
    await runIndex([repoRoot, "--structural-only"]);
    steps.push({ step: "index", status: "structural" });
  } else {
    // Full mode: structural + SCIP
    await runIndex([repoRoot]);
    steps.push({ step: "index", status: "full" });
  }

  output("setup", { repoRoot, steps });
}

/**
 * Hooks config that references portable scripts in .ariadne/hooks/.
 * These scripts resolve the ariadne binary dynamically at runtime.
 */
function generateHooksConfig(): object {
  return {
    hooks: {
      PreToolUse: [
        {
          matcher: "Edit|Write",
          hooks: [
            {
              type: "command",
              command: "bash .ariadne/hooks/pre-edit-impact.sh",
            },
          ],
        },
      ],
      PostToolUse: [
        {
          matcher: "Edit|Write",
          hooks: [
            {
              type: "command",
              command: "bash .ariadne/hooks/post-edit.sh",
            },
          ],
        },
        {
          matcher: "Bash",
          hooks: [
            {
              type: "command",
              command: "bash .ariadne/hooks/post-test.sh",
            },
          ],
        },
      ],
      Stop: [
        {
          hooks: [
            {
              type: "command",
              command: "bash .ariadne/hooks/stop-verify.sh",
            },
          ],
        },
      ],
    },
  };
}

function generateMcpConfig(): object {
  // Dev: resolve MCP server from monorepo.
  // Path differs between source (src/commands/) and dist (dist/):
  //   from src/commands/setup.ts: ../../.. → packages/, + mcp/src/index.ts
  //   from dist/index.js:         ../..   → packages/, + mcp/src/index.ts
  const candidates = [
    join(import.meta.dir, "..", "..", "..", "mcp", "src", "index.ts"),
    join(import.meta.dir, "..", "..", "mcp", "src", "index.ts"),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return {
        mcpServers: {
          ariadne: {
            command: "bun",
            args: ["run", resolve(candidate)],
            env: { ARIADNE_ROOT: "." },
          },
        },
      };
    }
  }
  // npm: use bunx to resolve the ariadne-mcp package
  return {
    mcpServers: {
      ariadne: {
        command: "bunx",
        args: ["ariadne-mcp"],
        env: { ARIADNE_ROOT: "." },
      },
    },
  };
}
